### PR TITLE
Added exception for hidden and corrected display of domains

### PR DESCRIPTION
**Pull request by ludeeus**
In the next version of the updater users vil have an option to set `hidden` attribute.
This change will make sure that attribute is not published to the card.

### CODE REVIEW

**Comment by ludeeus** [comment]
uuups... I based this of my branch for #5

**Review by ciotlosm — APPROVED** [review]
Looks good, but usually you would go for 0.2.0 as you're adding some minor functionality. Last fragment from version number is usually for bug fix minor patches.

**Comment by ludeeus** [comment]
This is just changes:
- the "headers"
- hides `hidden` attribute
- making sure the services are not executing twice.

No new functionality is added here?

**Comment by ciotlosm** [comment]
My bad, I thought the static domain was a new thing. Carry on :-)

**Comment by ludeeus** [comment]
"static domain" are just a visual change so it say "Custom Cards" and "Custom Components" instead of "Custom Updater" :)

**Pull request merged**
